### ISSUE TITLE
Add link to GitHub repo on addon page

### ISSUE THREAD

**Issue by shanet** [Vulpelo/hide-youtube-shorts#1]
Thanks for publishing this addon. It works great!

Before installing an addon I always try to take a quick look at it's source. As far as I can tell, there's no link to this repo from the addon's page: https://addons.mozilla.org/en-US/firefox/addon/hide-youtube-shorts.

For something that's licensed under the GPL, it would be best if the "homepage" link on the addon page contained a link to this repo so people can more easily find the source code. It's also helpful for people to know where to open issues / pull requests.

**Comment by Vulpelo** [comment]
Thank you for the info.
On addon's page I have added a link to the repo in the description.
