### ISSUE TITLE
Name of creator still displays for shorts in list view

### ISSUE THREAD

**Issue by SeinopSys** [Vulpelo/hide-youtube-shorts#12]
Thank you for this extension! It seems to work great in the Grid layout, however, when switching to the List view using the button in the top right, the name of the creator who uploaded the short lingers around despite the short being removed:

![Screenshot of a YouTube Subscriptions page in List view with Shorts videos hidden, while the name of the creator who posted the short remains visible](https://user-images.githubusercontent.com/3200580/236652566-a054e754-6866-47de-9841-6a1335b6c17e.png)

**Comment by Vulpelo** [comment]
Thank you for addressing the issue. The new version (1.2.7) with a fix was uploaded to add-ons store.

**Comment by SeinopSys** [comment]
Can confirm this is working now, thank you for the quick fix!
