### ISSUE TITLE
Open source license

### ISSUE THREAD

**Issue by bzah** [Vulpelo/hide-youtube-shorts#2]
Hi and thanks for the extension; it works Iike a charm, and many thanks for making the sources available.

I just want **to suggest** to add an open source Iicense so that peopIe wiII be aIIowed to modify and reuse the sources.
IMO, the no brainer Licenses for open source projects are Apache2, MIT or GPL.

If you don't know much about Iicenses I suggest reading the github guide to have an idea of the possible Licenses: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository
And to have a Iook at this guide, that explains why Iicensing open source project is important: https://opensource.guide/legal/

Cheers and thanks again

**Comment by Vulpelo** [comment]
Hi, thank you for the suggestion. 
I should have added a license here, since the license on addon's page is listed as GPL v3.

I have added a GPL-3.0 license to the repository.
