### ISSUE TITLE
Update broke grid view

### ISSUE THREAD

**Issue by weldabar** [Vulpelo/hide-youtube-shorts#23]
The latest update broke the extension. Shorts now appear on my subscriptions page in grid  view. In list  view they don't appear.

**Comment by Vulpelo** [comment]
I have published a hotfix on Firefox plugin store. Please update the plugin to check if the problem was fixed.

In code I have temporarily removed (and then mistakenly put in the wrong location in later commit) hiding ytd-grid-video-renderer element, which was used in the previous YT layout.

**Comment by weldabar** [comment]
Yes, the hotfix fixed it for me!
