### ISSUE TITLE
Hide in Notifications menu

### ISSUE THREAD

**Issue by skotsj** [Vulpelo/hide-youtube-shorts#27]
Would really love if it could filter in Notifications menu, seems a chrome only extension can do that but I use firefox :)

**Comment by zappbrannigan34** [comment]
shorts still in menu in chrome

**Comment by Vulpelo** [comment]
@zappbrannigan34  
Hiding shorts in notifications menu still works on my side. So either you don't have "Hide Shorts notifications" option selected in addons menu or there must be a new feature slowly rolling out to some users. 
I will look into it more once the feature reaches me.
