### ISSUE TITLE
Firefox for Android compatibility

### ISSUE THREAD

**Issue by Rybeusz100** [Vulpelo/hide-youtube-shorts#35]
Any chance of making it compatible with Firefox for Android?

**Comment by Vulpelo** [comment]
Sure, I will look into that, thanks.

**Comment by Vulpelo** [comment]
I have tested current version of the plugin (1.6.4) on "Firefox Nightly" and seems to be working correctly. 

On Mozilla's addon store I have added Android as a compatible device for the plugin, so soon (depending on how long review by mozilla) should be avaliable for download directly from the store.

**Comment by Rybeusz100** [comment]
It's already available, thanks a lot!
