### ISSUE TITLE
Option to hide Live vids

### ISSUE THREAD

**Issue by mrx23dot** [Vulpelo/hide-youtube-shorts#43]
They are also waste of ton of time, and will show up after streaming is done.

**Comment by Vulpelo** [comment]
Thanks for opening an issue with feature request!
The feature will allow hiding live videos like requested and also hiding 'upcoming' videos. Both options will be available in the Experimental section of plugin's menu and off by default.

**Comment by Vulpelo** [comment]
Reopening, because I have noticed that live videos on Home/Subscription pages are displayed differently from those on dedicated LIVE page (in explore section on left panel) on which I was testing feature. Will check again and fix support for those main pages.

**Comment by Vulpelo** [comment]
Thanks for information. I will limit height and add a scrollbar into 'More' section

**Comment by Vulpelo** [comment]
Have updated menu, now with scrollbar. New version was requested to be published on mozilla addons and chrome web store.

![image](https://github.com/user-attachments/assets/ef28cde9-7ec8-4c50-bbd5-a70d47c1f60a)
![image](https://github.com/user-attachments/assets/b1d063ea-4ff5-470e-b8ec-ec9c88c6eea2)
