### ISSUE TITLE
New shorts menu on mobile

### ISSUE THREAD

**Issue by luposmi** [Vulpelo/hide-youtube-shorts#47]
Hi, 

there is a new YouTube shorts menu on mobile (m.youtube.com) which is not getting blocked by the extension. On my yt home page, it shows directly after the first video and includes 4 shorts each in a 2x2 grid. Would be nice to block this menu as well.

**Comment by Vulpelo** [comment]
Thanks for creating the issue. I am working on the fix and will add it to the 1.8.3 version.

**Comment by Grinizz** [comment]
Hello,

When the version will be deploy on the Mozilla store ?
I'm waiting with impatience the 1.8.3 version.

Thanks a lot

**Comment by Vulpelo** [comment]
Hello @Grinizz,

I have uploaded new version to Firefox Add-Ons, but it is still awaiting for a review from Mozilla. 
Normally it was taking them about 3 work days, so hopefully somewhere next week they will look at the new version. 

Thanks

**Comment by Vulpelo** [comment]
New version 1.8.3 has been approved on Firefox Addons and now is available for download.

**Comment by Grinizz** [comment]
Thanks a lot. It will be save my time :)

Thanks for engagement !
