### ISSUE TITLE
Spyware?!

### ISSUE THREAD

**Issue by mrx23dot** [Vulpelo/hide-youtube-shorts#50]
What do you have to say regarding this accusation?

https://www.grc.com/sn/sn-999-notes.pdf

**Comment by Vulpelo** [comment]
Hello,
The article is about different "Hide Youtube Shorts" extension on chrome store.

My extension on chrome has name "Hide shorts for Youtube™" and extension id: ankepacjgoajhjpenegknbefpmfffdic .
Also currently has 738 users not 100'000 like one in the article
